name: My First Git Hub Action
on: [push]
jobs:
  builds:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        python-version: [3.8, 3.0]
    steps:
    -  uses: action/checkout@v3
    -  name: setup up python
       uses: action/setup-python@v2
       with:
         python-version: ${{matrix.python-version}}
    -  name: install dependencies
       run: |
         python -m pip install -upgrade pip
         pip install pytest

    -  name: Run the test cases 
       run: |
         cd: src
         python -m pytest addition.py
